default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  schema_search_path: public
  template: template0
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: student

test:
  <<: *default
  database: student

production:
  <<: *default
  database: dac47vt0ejno5d
  username: teaaovciwsqgnu
  password: f9d03eb6fbcf468f3ffc329c0d7e6495c81bd043e26a587cae0197186215219a
  host: ec2-23-21-227-73.compute-1.amazonaws.com
  port: 5432
