# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d620f7eb0332ba222ae82c89e03f9247763acd01b57c0b6761c2a365278b202a61f1a7192c3397db83dbc42b964d2a6d071da9ea3f3c5b1be00c3270dd139d

test:
  secret_key_base: 8644dc65abddbee817cdfec385bd207d2ddcadd2623ac2f03e3b5304e06de1df7dbc5dccc9cd74fb9b84b8583fb04668e2936733c62fb1e8137768ca90f0e9e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
